# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: Build Component Library
          command: yarn workspace @dss/proto build

      - save_cache:
          paths:
            - node_modules
            - packages/studio/node_modules
            - packages/proto/node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Lint Component Library
          command: yarn workspace @dss/proto lint

      - run:
          name: Test Component Library
          command: yarn workspace @dss/proto test

      - run:
          name: Build Demo App
          command: yarn workspace app build

      - run:
          name: Run Visual Tests
          command: yarn workspace @dss/proto run chromatic
